# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: dezoomcamp
channels:
  - conda-forge
dependencies:
  - python >=3.9,<3.10
  - ipykernel
  - jupyter
  - pandas
  - pyarrow
  - sqlalchemy
  - pgcli
  - psycopg2-binary 
  - pip
  # module2
  - mage-ai
  - google-cloud-bigquery
  # workshop 1
  - 'dlt[duckdb]'
  - 'dlt[parquet]'
  - parquet
  - dlt[bigquery]
  