# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: dezoomcamp
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - jupyter
  - pandas>=2.2
  - pyarrow
  - sqlalchemy>=2.0
  - pgcli
  - psycopg2-binary 
  - connectorx
  - polars
  - diagrams
  - pip
  # module2 mage
  - google-cloud-bigquery
  # workshop 1 dlthub
  - streamlit
  # module3 dwh
  - pandas-gbq
  - fastparquet 
  - nodejs>=20,<21
  - mystmd
  # module4 dbt
  - dbt-core
  - dbt-bigquery
  - dbt-postgres
  - dbt-duckdb
  # module5 spark
  # conda-forge does not carry matching pyspark version
  # module6 kafka
  - kafka-python
  - requests
  - avro
  - fastavro
  - pip:
    # workshop 1 dlthub
    - bigquery
    - dlt
    - 'dlt[duckdb]'
    - 'dlt[parquet]'
    - 'dlt[bigquery]'
    # module5 spark
    - pyspark==3.5.1
    # module6 kafka
    - confluent_kafka
    - faust-streaming
