# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: dezoomcamp
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - jupyter
  - pandas>=2.2
  - pyarrow
  - sqlalchemy>=2.0
  - pgcli
  - psycopg2-binary 
  - pip
  # module2 mage
  - google-cloud-bigquery
  # workshop 1 dlthub
  - streamlit
  - pip:
    - dlt
    - 'dlt[duckdb]'
    - 'dlt[parquet]'
    - 'dlt[bigquery]'
  # module3 dwh
  - pandas-gbq
  - fastparquet 
  - nodejs>=20,<21
  - mystmd
