services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPW}
      - POSTGRES_DB=${PGDB}
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "${PGPort}:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMINUSER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMINPW}
    ports:
      - "${PGADMINPort}:80"
    
  ingest-data-zones:
    build: .
    command:
      - --user=${PGUSER}
      - --password=${PGPW} 
      - --host=${DB}  
      - --port=${PGPort}
      - --db=${PGDB} 
      - --table_name=zones 
      - --url=https://s3.amazonaws.com/nyc-tlc/misc/taxi+_zone_lookup.csv

  ingest-data:
    build: .
    command:
      - --user=${PGUSER}
      - --password=${PGPW}
      - --host=${DB} 
      - --port=${PGPort} 
      - --db=${PGDB} 
      - --table_name=yellow_tripdata 
      - --url=https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2021-01.csv